### ISSUE TITLE
Problems with in-text citations 

### ISSUE THREAD

**Issue by Aaronw88** [pr-omethe-us/ussci-latex-template#1]
Hello, 

So I could be missing something and/or making a mistake somewhere; however, when I run this template the in-text citations appear as [author year] in stead of as a single number. For example, referencing the Zhao 2013 paper via ('\cite{Zhao2013}') yields: [Zhao2013] within the text. For a typical combustion and flame paper, the in-text citation should appear as [1], [1-10], [1-10,25], etc. I believe that this is typically handled in an elsarticle.cls file that employs natbib, which allows for the "short&compress" option (e.g. '\usepackage[sort&compress]{natbib}'). Is there a way to implement something similar here? Or is it already built in and I'm just missing it. Any help you can provide with this would be appreciated.

**Comment by rwest** [comment]
You have to use  `biber` not `bibtex`.
Maybe this should be made clear in the readme

**Comment by Aaronw88** [comment]
Thank you for your quick response.

I admit that I was using bibtex at first; however, after changing over to
biber, I saw no change in the result.

I'm using Texmaker with MiKTeX2.9. Under options, configure Texmaker, I
changed the line next to Bib(la)tex to biber. The file will compile
successfully and produced a PDF; however, the in-text citations still
appear as they did before (e.g. [Zhoa2013] instead of [1]).

Perhaps I'm simply missing one or two other simple options that need to be
selected.

Again, any help you can provide would be much appreciated.

Take care.

Aaron

**Comment by bryanwweber** [comment]
Can you please attach your LaTeX and .bib files here?

**Comment by Aaronw88** [comment]
The LaTeX and .bib files I'm using are in the attached folder. Whether I
use the "template.bib" or "cnf_bbP_bib.bib" file, I still see the same
issue.

Please let me know if there is anything further you require.

Again, thank you for your help, I greatly appreciate it.

Take care.

Aaron

**Comment by bryanwweber** [comment]
I think you have to log in to GitHub to attach files, I don't see anything on this post.

**Comment by Aaronw88** [comment]
Sorry, here are the files.



[LaTeX_bib_files.zip](https://github.com/pr-omethe-us/ussci-latex-template/files/2776727/LaTeX_bib_files.zip)

**Comment by Aaronw88** [comment]
So, I'm not specifically sure why, but I seem to have resolved the issue. I believe it was a result of having MikTex and/or biber in more than one location on my machine. After ensuring there was only one set (and path to) these files, the citations appeared correctly in the PDF. Thank you again for helping with this.

**Comment by bryanwweber** [comment]
Glad it is resolved. Sometimes, clearing the temporary files (`.aux`, `.bbl`, etc.) can also help resolve issues like this.
