### ISSUE TITLE
Relicense as CC-0

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/ussci-latex-template#4]
Hey @kyleniemeyer how would you feel about relicensing this as CC-0? I don't feel a need to attributed for this, and I'd rather it was more public.

**Comment by kyleniemeyer** [comment]
I suppose that's fine - but do you think the current license is actually impeding anything?

**Comment by bryanwweber** [comment]
No, I was just looking at it today to get it ready for this year's papers and realized the attribution is kinda meaningless... How does one attribute a template?

**Comment by kyleniemeyer** [comment]
I don't know that it would ever come up, really, but I guess for the same reason I don't see the point of changing 😄

**Comment by bryanwweber** [comment]
Closed by #7
